### ISSUE TITLE
Feature Request: Move/Copy built-in commands

### ISSUE THREAD

**Issue by andrew-luminal** [fugue/zim#13]
### copy

Copies files/directories using `cp`. Suggested syntax:

```
commands:
- copy
    src: [src]
    dest: [dest]
```

### move

Moves files/directories using `mv`. Suggested syntax:

```
commands:
- move
    src: [src]
    dest: [dest]
```
