### ISSUE TITLE
Feature Request: ROOT environment variable

### ISSUE THREAD

**Issue by andrew-luminal** [fugue/zim#16]
### `ROOT`

The root directory (where `artifacts` lives). Useful to avoid having to do `../../artifacts`, etc, could just do `${ROOT}/artifacts`. `ARTIFACTS_DIR` could also work? This will come into particular use since I'm intending on nesting  packages, ie `src/viz_packages/viz_renderer/component.yaml` and I'd like to avoid `../../../artifacts`, especially since that'll break if I later move them. Example rules where this would be useful:

Before
```
rules
  dist:
    requires:
      - rule: build
    native: true
    command: |
      if [ ! -d "dist" ]; then tar -zxf ../../artifacts/${NAME}.tgz; fi

  clean:
    commands:
      - remove: dist
      - remove: ../../artifacts/${NAME}.tgz
      - remove: node_modules
      - remove: ../../artifacts/${NAME}.node_modules.tgz
```

```
rules
  dist:
    requires:
      - rule: build
    native: true
    command: |
      if [ ! -d "dist" ]; then tar -zxf ${ROOT}/artifacts/${NAME}.tgz; fi

  clean:
    commands:
      - remove: dist
      - remove: ${ROOT}/artifacts/${NAME}.tgz
      - remove: node_modules
      - remove: ${ROOT}/artifacts/${NAME}.node_modules.tgz
```
