### ISSUE TITLE
Feature Request: Allow for open-ended, long running requests

### ISSUE THREAD

**Issue by andrew-luminal** [fugue/zim#17]
This request may be out-of-scope for Zim, but wanted to open the discussion anyways:

There are many cases where a live-reloading build is useful for development, but Zim seems to be more catered to producing build artifacts. 

1. Would it be possible to have Zim run a process that never completes?
2. Would it be possible for Zim to spawn multiple additional shells to create live-reloads on dependencies?

Ways this might work
```
rules:
  build_livereload:
    leave_open: true
    native: true
    commands:
      - run: yarn && yarn start

  build_livereload_all:
    leave_open: true
    requires:
      - component: dependency
        rule: build_livereload
      - rule: build_livereload  
```
