### ISSUE TITLE
BUG/FEATURE: "when" conditional does not take into account the built-in vars. Apply built-ins in more places

### ISSUE THREAD

**Issue by andrew-luminal** [fugue/zim#24]
I was trying to use `ARTIFACTS_DIR` in the `when.script_succeeds` part of the config, but it output an empty string.

```
  deploy:
    native: true
    requires:
      - rule: build
    when:
      script_succeeds:
        with_output: NEEDS_UPDATE
        run: ${ARTIFACTS_DIR}/../makedeps/component_diff.sh ${NAME}
    commands:
      - run: ${ARTIFACTS_DIR}/../makedeps/component_deploy.sh ${NAME}
```
Second `ARTIFACTS_DIR` works, first does not.
