### ISSUE TITLE
Comments do not work in multiline bash commands

### ISSUE THREAD

**Issue by jaspervdj-luminal** [fugue/zim#30]
It seems like this case is not handled correctly:

```
name: helloworld
rules:
  build:
    inputs:
    - "hello.c"
    outputs:
    - ${NAME}
    command: |
      gcc hello.c
      # Move the thing.
      mv a.out ${OUTPUT}
```

The last line is not executed.
